name: init
on:
  create:

permissions:
  contents: write
  issues: write
jobs:
  initialize:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - run: echo "Hello World"
